[theme]
theme = "gruvbox-light"

[icons]
icons = "awesome"

[[block]]
block = "cpu"
interval = 1
format = "$utilization.eng()"
format_alt = "$frequency.eng() \\|$boost.str()"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "$mem_used.eng(3,B,M)/$mem_avail.eng(3,B,M)($mem_used_percents.eng(2))"
format_swap = "$swap_used.eng(3,B,M)/$swap_total.eng(3,B,M)($swap_used_percents.eng(2))"
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = "$available.eng(2) / $total"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "enp6s0"
format = "$speed_down.eng(3,B,K)$speed_up.eng(3,B,K)"
interval = 2


[[block]]
block = "time"
interval = 60
format = "%a %-d %b %I:%M %P"
timezone = "Africa/Cairo"
