theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
format_mem = "{mem_used} ({mem_used_percents})"
format_swap = "{swap_used} ({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "{icon} {used} / {total}"
unit = "GB"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "enp6s0"
format = "{ip} {speed_up;K*b} {speed_down;K*b}"
interval = 2

[[block]]
block = "time"
interval = 60
format = "%a %-d %b %I:%M %P"
