[
  ./gnupg.nix
  ../../../modules/programs/alacritty.nix
  ../../../modules/programs/zsh.nix
  ../../../modules/programs/direnv.nix
  ../../../modules/programs/bat.nix
  ../../../modules/programs/btop.nix
  ../../../modules/programs/eza.nix
  ../../../modules/programs/git.nix
  ../../../modules/programs/gh.nix
  ../../../modules/programs/ghostty.nix
  ../../../modules/programs/zoxide.nix
  ../../../modules/programs/atuin.nix
  ../../../modules/programs/starship.nix
  ../../../modules/programs/firefox.nix
  ../../../modules/programs/jujutsu.nix
  ../../../modules/programs/zellij.nix
  ../../../modules/programs/spotify.nix
  ../../../modules/programs/windsurf.nix
  #../../../modules/programs/vscode
  ../../../modules/programs/wezterm
  ../../../modules/programs/neovim
]
